name: Cipher Algorithm Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: git
        run: |
          git config --global user.name github.actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: execute py script # run the run.py to get the latest data
        run: |
          python CaesarCipher_test.py
      - name: commit
        run: |
          git commit -am "logging test result ${GITHUB_SHA:8}" || true
          git push --force origin HEAD:$GITHUB_REF || true 